### ISSUE TITLE
Plugin API proposal

### ISSUE THREAD

**Issue by fmmaks666** [h4cktoria/Marinette#5]
As we discussed in game, structured plugin API will suit Marinette more. So I propose simpler API, which focuses on stability and security

## Plugin definition

```javascript
m = get_custom_object
// Manual way:
meta = {
	"internal": "my_plugin"
	"name": "My Plugin",
	"author": "John Doe",
	"permission": 3,
}
// Function way
meta = m.createMeta("myplugin", "My Plugin", "John Doe", 3)

api = m.registerPlugin(meta, "mypluginsecret")
```

`meta` is a map containing required information to create plugin.

- `string internal`: internal name of plugin, mustn't contain any special symbols or spaces
- `string name`: User facing name of Plugin
- `string author`: Who created plugin
- `int permission`: Defines limitations for plugin. 0 - Root, 2 - Sessions, 3 - Basic

`registerPlugin` registers a plugin with metadata and plugin's secret. Returns `null` on failure and `API` on success

- Depending on `permission` API will have more or less methods
- `string secret` is password for Plugins's state map. Used to prevent stealing data from another plugin. Plugins with limitations 0 can access any state

## Accessing state

```javascript
// To access state using password
state = api.getState(meta.internal, "mypluginsecret")
// If limitations are 0 then you can access any state
state = api.getStateAsRoot("any_plugin")
// State is just a map
state.something = "Thing!"
```

`getState` gets state for specified plugin (`string internal`) with password (`string secret`). Returns `map` on success, `null` on failure

`getStateAsRoot` gets state of any plugin.

## Registering commands Idea. 1
```javascript
my_command = function(args)
	api.arguments(args, 2) // API is stored in globals
	api.Console.log("Hello!")
end function

api.registerCommand("mycommand", @my_command, ["mc"])
```

`registerCommand` register commands. First argument is name of command, second is function reference, third is aliases (optinal)

## Registering commands Idea. 2
```javascript
api.Commands.my_command = function(args)
	api.arguments(args, 2) // API is stored in globals
	api.Console.log("Hello!")
end function
```

Simpler way. Command name mustn't contain spaces.

#### Other
- Plugin may have init function to initialize state

**Comment by fmmaks666** [comment]
I'm working on implementation. I aim for 2nd idea for command registration. Let me know if there are any problems with proposal.
PS. @h4cktoria check your Matrix sometimes, please

**Comment by h4cktoria** [comment]
Everything seems good. Thanks a lot for your commitment!
